vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

# config/packages/vich_uploader.yaml
    mappings:
            poster_file:
                    # alias qui nous permet d'accéder à nos images depuis le navigateur
                    uri_prefix: '%uploads_files%'
                    # Chemin vers le dossier de stockage
                    upload_destination: '%kernel.project_dir%/public%uploads_files%'
                    namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

